<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="10" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="66" started-at="2017-08-10T19:14:10Z" finished-at="2017-08-10T19:14:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="66" started-at="2017-08-10T19:14:10Z" finished-at="2017-08-10T19:14:10Z">
      <class name="co.unbosque.isii.calculadora_pruebas.NewTest">
        <test-method status="PASS" signature="debeDividirCorrectamente()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="debeDividirCorrectamente" duration-ms="12" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- debeDividirCorrectamente -->
        <test-method status="PASS" signature="debeMultiplicarCorrectamente()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="debeMultiplicarCorrectamente" duration-ms="2" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- debeMultiplicarCorrectamente -->
        <test-method status="PASS" signature="debeRestarCorrectamente()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="debeRestarCorrectamente" duration-ms="2" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- debeRestarCorrectamente -->
        <test-method status="PASS" signature="debeSumarCorrectamente()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="debeSumarCorrectamente" duration-ms="3" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- debeSumarCorrectamente -->
        <test-method status="PASS" signature="laOperacionDivisionExiste()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="laOperacionDivisionExiste" duration-ms="1" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laOperacionDivisionExiste -->
        <test-method status="PASS" signature="laOperacionMultiplicacionExiste()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="laOperacionMultiplicacionExiste" duration-ms="1" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laOperacionMultiplicacionExiste -->
        <test-method status="PASS" signature="laOperacionRestaExiste()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="laOperacionRestaExiste" duration-ms="1" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laOperacionRestaExiste -->
        <test-method status="PASS" signature="laOperacionSumaExiste()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="laOperacionSumaExiste" duration-ms="1" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laOperacionSumaExiste -->
        <test-method status="PASS" signature="laSeparacionDeNumerosExiste()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="laSeparacionDeNumerosExiste" duration-ms="2" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laSeparacionDeNumerosExiste -->
        <test-method status="FAIL" signature="laSeparacionDeOperadoresExiste()[pri:0, instance:co.unbosque.isii.calculadora_pruebas.NewTest@3c756e4d]" name="laSeparacionDeOperadoresExiste" duration-ms="4" started-at="2017-08-10T14:14:10Z" finished-at="2017-08-10T14:14:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<-> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<-> but was:<>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at co.unbosque.isii.calculadora_pruebas.NewTest.laSeparacionDeOperadoresExiste(NewTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laSeparacionDeOperadoresExiste -->
      </class> <!-- co.unbosque.isii.calculadora_pruebas.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
